name: Update README with Current Time

on:
  schedule:
    - cron: '*/15 * * * *'  # 每 15 分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update README with Current Time
      run: |
        CURRENT_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
        echo "Updating README with the current time: $CURRENT_TIME"
        sed -i "/<!-- DYNAMIC_TIME -->/c\Current Time: $CURRENT_TIME" README.md

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --global user.email "majuejin@gmail.com"
        git config --global user.name "vestjin"
        git add README.md
        git commit -m "Updated time in README"
        git push https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git HEAD:main
